Updated provider/steam to fix InvalidMarkupException errors
InvalidMarkupException: "The current node list is empty." was thrown
because it was not retried because it was not part of the fetch-retry
loop. That is, the parsing occurs after the fetch, so it was useless
throwing a retryable exception at that point.